[package]
name = "tex_atlas_2d"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "A crate for working with TexImage2D objects."


[dependencies]
stb_image = "0.2.2"
